
======================================================================
ERROR test_halt.chpl: {}
----------------------------------------------------------------------
test_halt.chpl:9: error: halt reached - array index out of bounds: (0)

======================================================================
FAIL test_halt.chpl: {}
----------------------------------------------------------------------
AssertionError: assert failed - '2' != '3.0'

----------------------------------------------------------------------
Run 3 tests

FAILED failures = 1 errors = 1 
