bug: return in module not flagged as error
