Halt reached: test_begin_error_lineno.chpl:10
a thread is out of control
