  called from badcall.v:3
  called from badcall.v:3
  called from badcall.v:4
  called from badcall.v:4
 called from 4 in __init at assign2.v:1
__init::self(assign2.v:1) ( C (assign2.v:1) )
badcall.v:2: expression has no type
badcall.v:2: expression has no type
badcall.v:3: expression has no type
badcall.v:3: expression has no type
badcall.v:4: expression has no type
badcall.v:4: expression has no type
f::c2(assign2.v:3) ( C (assign2.v:1) )
fail: program does not type
function __init assign2.v:1
function __init assign2.v:1
function f assign2.v:3
globals
user::c1(assign2.v:2) ( C (assign2.v:1) )
